[package]
name = "ixgenup"
version = "1.0.0"
authors = ["Owner <getdevved@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.3"}
tokio = { version = "1", features = ["full"] }
